#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Mahmoud Mohamed   #
#                                   #
#####################################

version: "3.8"

# containers #
services:

  # server container #
  server:

    image: 'nginx:stable-alpine'

    ports:
      - '8000:80'

    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - php
      - mysql

  # php container #
  php:

    build:
      context: .
      dockerfile: ./dockerFiles/php.dockerfile

    volumes:
      - ./src:/var/www/html:delegated

  # mysql container #
  mysql:

    image: 'mysql:5.7'

    env_file:
      - ./env/mysql.env

  # composer container #
  composer:

    build:
      context: ./dockerFiles
      dockerfile: composer.dockerfile

    volumes:
      - ./src:/var/www/html